### ISSUE TITLE
Feature: Complete UV-first CLI architecture from Issue #1

### ISSUE THREAD

**Issue by safurrier** [safurrier/cookiecutter-ai-conventions#37]
Implement the UV tool installation feature described in Issue #1. This transforms the project from a one-time setup into a living development tool with global CLI commands.

### 1. Research Click framework best practices
- [ ] Review Click documentation for command groups
- [ ] Research Click testing patterns
- [ ] Investigate Click shell completion setup
- [ ] Look at examples of well-structured Click CLIs

### 2. Research uv tool installation
- [ ] Understand `uv tool install` mechanics
- [ ] Research entry points configuration
- [ ] Test local tool installation workflow
- [ ] Document any limitations or requirements

### 1. Update pyproject.toml in template:
```toml
[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = "{{ cookiecutter.project_name }}"

[project.scripts]
ai-conventions = "ai_conventions.cli:main"
capture-learning = "ai_conventions.capture:main"
sync-conventions = "ai_conventions.sync:main"

[tool.uv]
dev-dependencies = ["textual>=0.47.0", "rich>=13.0", "click>=8.0"]
```

### 2. Create CLI module structure:
```python
# {{cookiecutter.project_slug}}/ai_conventions/__init__.py
from .cli import main
from .capture import capture_learning
from .sync import sync_conventions

# {{cookiecutter.project_slug}}/ai_conventions/cli.py
import click
from pathlib import Path

@click.group()
def main():
    """AI Conventions management tool."""
    pass

@main.command()
def status():
    """Check installation status."""
    claude_path = Path.home() / '.claude'
    if (claude_path / 'CLAUDE.md').exists():
        click.echo("✅ Conventions installed to Claude")
    else:
        click.echo("❌ Not installed to Claude")
```

## Acceptance Criteria

- [ ] Research phase completed with findings documented
- [ ] Users can run `uv tool install .` in their conventions repo
- [ ] Commands available globally after installation
- [ ] `capture-learning "pattern" --domain python` works
- [ ] `sync-conventions` updates provider installations
- [ ] Shell completions generated

## MODEST Principles
- **Modularity**: Each command is a separate module
- **Dependency Injection**: Paths and configs passed explicitly
- **Single Responsibility**: Each command does one thing

## TDD Approach
1. Research Click testing patterns
2. Write tests for CLI commands first
3. Test installation process
4. Test command availability
5. Implement features to pass tests

Related to #15 (1.0 Roadmap)
