### ISSUE TITLE
🧪 Add End-to-End Installation Tests

### ISSUE THREAD

**Issue by safurrier** [safurrier/cookiecutter-ai-conventions#53]
**Type**: Testing  
**Priority**: High  

## Description
Create automated tests that verify the entire installation flow works correctly from start to finish.

## Acceptance Criteria
- [ ] E2E test runs in CI/CD pipeline
- [ ] Tests cover all provider combinations
- [ ] Tests verify correct file generation
- [ ] Tests run in < 2 minutes
- [ ] Clear failure messages when tests fail

## Test Scenarios
```yaml
test_scenarios:
  - name: "Single Provider Install"
    inputs:
      project_name: "test-project"
      providers: ["claude"]
      templates: ["git"]
    expected_files:
      - ".ai/conventions.md"
      - ".ai/providers/claude.md"
      - ".ai/domains/git.md"
      
  - name: "Multiple Providers Install"
    inputs:
      project_name: "test-multi"
      providers: ["claude", "cursor", "windsurf"]
      templates: ["git", "writing"]
    expected_files:
      - ".ai/providers/claude.md"
      - ".ai/providers/cursor.md"
      - ".ai/providers/windsurf.md"
```

## Implementation
```python
# tests/test_e2e_installation.py
def test_single_provider_installation():
    """Test installation with single provider"""
    with tempfile.TemporaryDirectory() as tmpdir:
        result = subprocess.run([
            "cookiecutter",
            ".",
            "--no-input",
            f"--output-dir={tmpdir}",
            "project_name=test-project",
            "selected_providers=claude"
        ])
        assert result.returncode == 0
```
